export default {
  SELECTED_ADDRESS: 'SELECTED_ADDRESS',
  GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION',
  SELECTED_ADDRESS_SUCCESS: 'SELECTED_ADDRESS_SUCCESS',
  GET_CURRENT_LOCATION_SUCCESS: 'GET_CURRENT_LOCATION_SUCCESS',
  SELECTED_ADDRESS_ERROR: 'SELECTED_ADDRESS_ERROR',
  GET_CURRENT_LOCATION_ERROR: 'GET_CURRENT_LOCATION_ERROR',
  RESET_LOCATION: 'RESET_LOCATION',
};
