export default {
  CREATE_ADDRESS: 'CREATE_ADDRESS',
  CREATE_ADDRESS_ERROR: 'CREATE_ADDRESS_FAILED',
  CREATE_ADDRESS_SUCCESS: 'CREATE_ADDRESS_SUCCESS',
  LOAD_ADDRESS: 'LOAD_ADDRESS',
  LOAD_ADDRESS_SUCCESS: 'LOAD_ADDRESS_SUCCESS',
  LOAD_ADDRESS_ERROR: 'LOAD_ADDRESS_ERROR',
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  UPDATE_ADDRESS_SUCCESS: 'UPDATE_ADDRESS_SUCCESS',
  UPDATE_ADDRESS_ERROR: 'UPDATE_ADDRESS_ERROR',
  GET_ADDRESS_BY_KEY: 'GET_ADDRESS_BY_KEY',
  RESET_STATUS: 'RESET_STATUS',
  RESET_KEY: 'RESET_KEY',
};
